export const GET_ALL_USERS_START = 'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
export const ADD_USER_TO_CHAT = 'ADD_USER_TO_CHAT';
export const CLEAR_USER_TO_CHAT = 'CLEAR_USER_TO_CHAT';