export const GET_ALL_USERS_START = 'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
export const ADD_USER_ID = 'ADD_USER_ID';
export const CLEAR_USER_ID = 'CLEAR_USER_ID';